name: 'Delivery da Infraestrutura'

on:
  push:
    branches:
      - "development"

permissions:
  contents: read

jobs:
  terraform-dev:
    name: 'Infraestrutura - Terraform - Dev'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    if: github.ref == 'refs/heads/development'
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configura as credenciais da AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Instala Kubectl
      uses: Azure/setup-kubectl@v4.0.0

    - name: Instala Helm
      uses: Azure/setup-helm@v4

    - name: Configura o kubectl para o EKS
      run: aws eks --region us-east-1 update-kubeconfig --name eks-fiap-fastfood-dev

    - name: Instala o secrets-store-csi-driver
      run: |
            helm repo add secrets-store-csi-driver https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
            helm install -n kube-system csi-secrets-store secrets-store-csi-driver/secrets-store-csi-driver

    - name: Instala o secrets-store-csi-driver-provider-aws
      run: |
            helm repo add aws-secrets-manager https://aws.github.io/secrets-store-csi-driver-provider-aws
            helm install -n kube-system secrets-provider-aws aws-secrets-manager/secrets-store-csi-driver-provider-aws

    - name: Lista pods da namespace kube-system
      run: kubectl get pods --namespace kube-system
